package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strings"
	"unicode"

	"ans2go/pkg/asn1/analyzer"
	"ans2go/pkg/asn1/ast"
)

// ToGoIdent converts an ASN.1 hyphenated or camelCase identifier to an exported Go identifier.
func ToGoIdent(s string) string {
	if s == "" {
		return ""
	}
	// Handle negative drift rates in UTRANGPSDriftRate and UTRANGANSSDriftRate
	s = strings.ReplaceAll(s, "Drift-", "DriftNeg")

	parts := strings.FieldsFunc(s, func(r rune) bool {
		return r == '-' || r == '_'
	})
	var b strings.Builder
	for _, part := range parts {
		if part == "" {
			continue
		}
		runes := []rune(part)
		runes[0] = unicode.ToUpper(runes[0])
		b.WriteString(string(runes))
	}
	res := b.String()
	// Safeguard against empty or digit-start
	if len(res) > 0 && unicode.IsDigit(rune(res[0])) {
		res = "X" + res
	}
	return res
}

// Generator generates Go source code for a ResolvedModel.
type Generator struct {
	model   *analyzer.ResolvedModel
	pkgName string
	buf     bytes.Buffer
}

// New creates a new Generator.
func New(model *analyzer.ResolvedModel, pkgName string) *Generator {
	if pkgName == "" {
		pkgName = "asn1"
	}
	return &Generator{
		model:   model,
		pkgName: pkgName,
	}
}

// Generate produces formatted Go source code.
func (g *Generator) Generate() ([]byte, error) {
	g.buf.Reset()

	g.w("// Code generated by ans2go. DO NOT EDIT.\n\n")
	g.w("package %s\n\n", g.pkgName)
	g.w("import (\n")
	g.w("\t\"fmt\"\n")
	g.w("\t\"ans2go/pkg/uper\"\n")
	g.w(")\n\n")

	g.w("// Marshal encodes a UPER encodable value into bytes.\n")
	g.w("func Marshal(v uper.Encoder) ([]byte, error) {\n")
	g.w("\treturn uper.Marshal(v)\n")
	g.w("}\n\n")

	g.w("// Unmarshal decodes UPER bytes into a target value.\n")
	g.w("func Unmarshal(data []byte, v uper.Decoder) error {\n")
	g.w("\treturn uper.Unmarshal(data, v)\n")
	g.w("}\n\n")

	// Emit constant declarations
	g.emitConstants()

	// Emit all alphabets for VisibleString types
	g.emitAlphabets()

	// Emit all types and their codecs
	for _, typeName := range g.model.Order {
		typeDef := g.model.Types[typeName]
		if err := g.emitTypeDef(typeName, typeDef.Type); err != nil {
			return nil, fmt.Errorf("generating type %s: %w", typeName, err)
		}
	}

	src := g.buf.Bytes()
	formatted, err := format.Source(src)
	if err != nil {
		return src, fmt.Errorf("formatting generated code: %w\nSource:\n%s", err, string(src))
	}
	return formatted, nil
}

func (g *Generator) w(formatStr string, args ...interface{}) {
	fmt.Fprintf(&g.buf, formatStr, args...)
}

func (g *Generator) emitConstants() {
	if len(g.model.Constants) == 0 {
		return
	}
	// Sort constant names for deterministic output
	var keys []string
	for k := range g.model.Constants {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	g.w("// ASN.1 Value Definitions (Constants)\nconst (\n")
	for _, k := range keys {
		g.w("\t%s int64 = %d\n", ToGoIdent(k), g.model.Constants[k])
	}
	g.w(")\n\n")
}

func (g *Generator) emitAlphabets() {
	for _, typeName := range g.model.Order {
		typeDef := g.model.Types[typeName]
		if cs, ok := typeDef.Type.(*ast.CharacterStringType); ok && cs.Kind == "VisibleString" && len(cs.Alphabet) > 0 {
			g.w("var alphabet_%s = uper.BuildAlphabet([]string{", ToGoIdent(typeName))
			for i, item := range cs.Alphabet {
				if i > 0 {
					g.w(", ")
				}
				g.w("%q", item)
			}
			g.w("})\n\n")
		}
	}
}

func (g *Generator) goTypeStr(t ast.Type) string {
	switch typ := t.(type) {
	case *ast.ReferenceType:
		return ToGoIdent(typ.Name)
	case *ast.IntegerType:
		return "int64"
	case *ast.BooleanType:
		return "bool"
	case *ast.BitStringType:
		return "uper.BitString"
	case *ast.OctetStringType:
		return "[]byte"
	case *ast.CharacterStringType:
		return "string"
	case *ast.UTCTimeType:
		return "string"
	case *ast.NullType:
		return "uper.Null"
	case *ast.SequenceOfType:
		return "[]" + g.goTypeStr(typ.ElementType)
	case *ast.EnumeratedType:
		return "int"
	default:
		return "interface{}"
	}
}

func (g *Generator) emitTypeDef(name string, t ast.Type) error {
	goName := ToGoIdent(name)

	switch typ := t.(type) {
	case *ast.IntegerType:
		g.w("// %s represents ASN.1 INTEGER\n", goName)
		g.w("type %s int64\n\n", goName)
		g.emitIntegerCodec(goName, typ)

	case *ast.BooleanType:
		g.w("// %s represents ASN.1 BOOLEAN\n", goName)
		g.w("type %s bool\n\n", goName)
		g.emitBooleanCodec(goName)

	case *ast.BitStringType:
		g.w("// %s represents ASN.1 BIT STRING\n", goName)
		g.w("type %s uper.BitString\n\n", goName)
		g.emitBitStringCodec(goName, typ)

	case *ast.OctetStringType:
		g.w("// %s represents ASN.1 OCTET STRING\n", goName)
		g.w("type %s []byte\n\n", goName)
		g.emitOctetStringCodec(goName, typ)

	case *ast.CharacterStringType:
		g.w("// %s represents ASN.1 %s\n", goName, typ.Kind)
		g.w("type %s string\n\n", goName)
		g.emitCharStringCodec(goName, typ)

	case *ast.UTCTimeType:
		g.w("// %s represents ASN.1 UTCTime\n", goName)
		g.w("type %s string\n\n", goName)
		g.emitUTCTimeCodec(goName)

	case *ast.NullType:
		g.w("// %s represents ASN.1 NULL\n", goName)
		g.w("type %s uper.Null\n\n", goName)
		g.emitNullCodec(goName)

	case *ast.SequenceOfType:
		elemTypeStr := g.goTypeStr(typ.ElementType)
		g.w("// %s represents ASN.1 SEQUENCE OF\n", goName)
		g.w("type %s []%s\n\n", goName, elemTypeStr)
		g.emitSequenceOfCodec(goName, typ)

	case *ast.EnumeratedType:
		g.emitEnumeratedType(goName, typ)

	case *ast.ChoiceType:
		g.emitChoiceType(goName, typ)

	case *ast.SequenceType:
		g.emitSequenceType(goName, typ)

	default:
		return fmt.Errorf("unsupported AST type: %T", t)
	}

	return nil
}

func (g *Generator) emitIntegerCodec(goName string, typ *ast.IntegerType) {
	// EncodeUPER
	g.w("func (v *%s) EncodeUPER(w *uper.BitWriter) error {\n", goName)
	if typ.IsConstrained {
		g.w("\treturn w.WriteConstrainedInt(int64(*v), %d, %d)\n", typ.MinVal, typ.MaxVal)
	} else {
		g.w("\treturn w.WriteSemiConstrainedInt(int64(*v), 0)\n")
	}
	g.w("}\n\n")

	// DecodeUPER
	g.w("func (v *%s) DecodeUPER(r *uper.BitReader) error {\n", goName)
	if typ.IsConstrained {
		g.w("\tval, err := r.ReadConstrainedInt(%d, %d)\n", typ.MinVal, typ.MaxVal)
		g.w("\tif err != nil { return err }\n")
		g.w("\t*v = %s(val)\n", goName)
		g.w("\treturn nil\n")
	} else {
		g.w("\tval, err := r.ReadSemiConstrainedInt(0)\n")
		g.w("\tif err != nil { return err }\n")
		g.w("\t*v = %s(val)\n", goName)
		g.w("\treturn nil\n")
	}
	g.w("}\n\n")
}

func (g *Generator) emitBooleanCodec(goName string) {
	g.w("func (v *%s) EncodeUPER(w *uper.BitWriter) error {\n", goName)
	g.w("\tw.WriteBit(bool(*v))\n\treturn nil\n}\n\n")

	g.w("func (v *%s) DecodeUPER(r *uper.BitReader) error {\n", goName)
	g.w("\tval, err := r.ReadBit()\n\tif err != nil { return err }\n\t*v = %s(val)\n\treturn nil\n}\n\n", goName)
}

func (g *Generator) emitBitStringCodec(goName string, typ *ast.BitStringType) {
	minSize := typ.MinSize
	maxSize := typ.MaxSize
	if !typ.HasSize {
		minSize = 0
		maxSize = 65535
	}
	g.w("func (v *%s) EncodeUPER(w *uper.BitWriter) error {\n", goName)
	g.w("\treturn w.WriteBitString(uper.BitString(*v), %d, %d)\n}\n\n", minSize, maxSize)

	g.w("func (v *%s) DecodeUPER(r *uper.BitReader) error {\n", goName)
	g.w("\tbs, err := r.ReadBitString(%d, %d)\n\tif err != nil { return err }\n\t*v = %s(bs)\n\treturn nil\n}\n\n", minSize, maxSize, goName)
}

func (g *Generator) emitOctetStringCodec(goName string, typ *ast.OctetStringType) {
	minSize := typ.MinSize
	maxSize := typ.MaxSize
	if !typ.HasSize {
		minSize = 0
		maxSize = 65535
	}
	g.w("func (v *%s) EncodeUPER(w *uper.BitWriter) error {\n", goName)
	g.w("\treturn w.WriteOctetString([]byte(*v), %d, %d)\n}\n\n", minSize, maxSize)

	g.w("func (v *%s) DecodeUPER(r *uper.BitReader) error {\n", goName)
	g.w("\tb, err := r.ReadOctetString(%d, %d)\n\tif err != nil { return err }\n\t*v = %s(b)\n\treturn nil\n}\n\n", minSize, maxSize, goName)
}

func (g *Generator) emitCharStringCodec(goName string, typ *ast.CharacterStringType) {
	minSize := typ.MinSize
	maxSize := typ.MaxSize
	if !typ.HasSize {
		minSize = 1
		maxSize = 255
	}

	if typ.Kind == "IA5String" {
		g.w("func (v *%s) EncodeUPER(w *uper.BitWriter) error {\n", goName)
		g.w("\treturn w.WriteIA5String(string(*v), %d, %d)\n}\n\n", minSize, maxSize)

		g.w("func (v *%s) DecodeUPER(r *uper.BitReader) error {\n", goName)
		g.w("\ts, err := r.ReadIA5String(%d, %d)\n\tif err != nil { return err }\n\t*v = %s(s)\n\treturn nil\n}\n\n", minSize, maxSize, goName)
	} else {
		// VisibleString
		alphaRef := "nil"
		if len(typ.Alphabet) > 0 {
			alphaRef = "alphabet_" + goName
		}
		g.w("func (v *%s) EncodeUPER(w *uper.BitWriter) error {\n", goName)
		g.w("\treturn w.WriteVisibleString(string(*v), %s, %d, %d)\n}\n\n", alphaRef, minSize, maxSize)

		g.w("func (v *%s) DecodeUPER(r *uper.BitReader) error {\n", goName)
		g.w("\ts, err := r.ReadVisibleString(%s, %d, %d)\n\tif err != nil { return err }\n\t*v = %s(s)\n\treturn nil\n}\n\n", alphaRef, minSize, maxSize, goName)
	}
}

func (g *Generator) emitUTCTimeCodec(goName string) {
	g.w("func (v *%s) EncodeUPER(w *uper.BitWriter) error {\n", goName)
	g.w("\treturn w.WriteUTCTime(string(*v))\n}\n\n")

	g.w("func (v *%s) DecodeUPER(r *uper.BitReader) error {\n", goName)
	g.w("\ts, err := r.ReadUTCTime()\n\tif err != nil { return err }\n\t*v = %s(s)\n\treturn nil\n}\n\n", goName)
}

func (g *Generator) emitNullCodec(goName string) {
	g.w("func (v *%s) EncodeUPER(w *uper.BitWriter) error {\n\treturn nil\n}\n\n", goName)
	g.w("func (v *%s) DecodeUPER(r *uper.BitReader) error {\n\t*v = %s{}\n\treturn nil\n}\n\n", goName, goName)
}

func (g *Generator) emitSequenceOfCodec(goName string, typ *ast.SequenceOfType) {
	minSize := typ.MinSize
	maxSize := typ.MaxSize

	// EncodeUPER
	g.w("func (v *%s) EncodeUPER(w *uper.BitWriter) error {\n", goName)
	g.w("\tl := len(*v)\n")
	if typ.HasSize {
		g.w("\tif l < %d || l > %d {\n", minSize, maxSize)
		g.w("\t\treturn fmt.Errorf(\"%s slice length %%d out of bounds [%d, %d]\", l)\n", goName, minSize, maxSize)
		g.w("\t}\n")
		if minSize != maxSize {
			g.w("\tif err := w.WriteConstrainedInt(int64(l), %d, %d); err != nil { return err }\n", minSize, maxSize)
		}
	} else {
		g.w("\tif err := w.WriteLengthDeterminant(l); err != nil { return err }\n")
	}

	g.w("\tfor i := 0; i < l; i++ {\n")
	g.w("\t\telem := (*v)[i]\n")
	g.emitValueEncode("elem", typ.ElementType, "\t\t")
	g.w("\t}\n")
	g.w("\treturn nil\n}\n\n")

	// DecodeUPER
	g.w("func (v *%s) DecodeUPER(r *uper.BitReader) error {\n", goName)
	if typ.HasSize {
		if minSize == maxSize {
			g.w("\tlength := %d\n", minSize)
		} else {
			g.w("\tlenVal, err := r.ReadConstrainedInt(%d, %d)\n", minSize, maxSize)
			g.w("\tif err != nil { return err }\n")
			g.w("\tlength := int(lenVal)\n")
		}
	} else {
		g.w("\tlength, err := r.ReadLengthDeterminant()\n")
		g.w("\tif err != nil { return err }\n")
	}

	elemTypeStr := g.goTypeStr(typ.ElementType)
	g.w("\t*v = make([]%s, length)\n", elemTypeStr)
	g.w("\tfor i := 0; i < length; i++ {\n")
	g.w("\t\tvar elem %s\n", elemTypeStr)
	g.emitValueDecode("elem", typ.ElementType, "\t\t")
	g.w("\t\t(*v)[i] = elem\n")
	g.w("\t}\n")
	g.w("\treturn nil\n}\n\n")
}

func (g *Generator) emitEnumeratedType(goName string, typ *ast.EnumeratedType) {
	g.w("// %s represents ASN.1 ENUMERATED\n", goName)
	g.w("type %s int\n\n", goName)

	g.w("const (\n")
	for _, it := range typ.Items {
		g.w("\t%s_%s %s = %d\n", goName, ToGoIdent(it.Name), goName, it.Value)
	}
	for _, it := range typ.ExtensionItems {
		g.w("\t%s_%s %s = %d\n", goName, ToGoIdent(it.Name), goName, it.Value)
	}
	g.w(")\n\n")

	// EncodeUPER
	g.w("func (v *%s) EncodeUPER(w *uper.BitWriter) error {\n", goName)
	if typ.Extensible {
		g.w("\tswitch *v {\n")
		for rootIdx, it := range typ.Items {
			g.w("\tcase %s_%s:\n", goName, ToGoIdent(it.Name))
			g.w("\t\tw.WriteBit(false)\n")
			g.w("\t\treturn w.WriteConstrainedInt(%d, 0, %d)\n", rootIdx, len(typ.Items)-1)
		}
		for extIdx, it := range typ.ExtensionItems {
			g.w("\tcase %s_%s:\n", goName, ToGoIdent(it.Name))
			g.w("\t\tw.WriteBit(true)\n")
			g.w("\t\treturn w.WriteNormallySmallNonNegativeWholeNumber(%d)\n", extIdx)
		}
		g.w("\tdefault:\n\t\treturn fmt.Errorf(\"unknown enum value %%d for %s\", *v)\n", goName)
		g.w("\t}\n}\n\n")
	} else {
		g.w("\tswitch *v {\n")
		for rootIdx, it := range typ.Items {
			g.w("\tcase %s_%s:\n", goName, ToGoIdent(it.Name))
			g.w("\t\treturn w.WriteConstrainedInt(%d, 0, %d)\n", rootIdx, len(typ.Items)-1)
		}
		g.w("\tdefault:\n\t\treturn fmt.Errorf(\"unknown enum value %%d for %s\", *v)\n", goName)
		g.w("\t}\n}\n\n")
	}

	// DecodeUPER
	g.w("func (v *%s) DecodeUPER(r *uper.BitReader) error {\n", goName)
	if typ.Extensible {
		g.w("\tisExt, err := r.ReadBit()\n\tif err != nil { return err }\n")
		g.w("\tif !isExt {\n")
		g.w("\t\tidx, err := r.ReadConstrainedInt(0, %d)\n\t\tif err != nil { return err }\n", len(typ.Items)-1)
		g.w("\t\tswitch idx {\n")
		for rootIdx, it := range typ.Items {
			g.w("\t\tcase %d:\n\t\t\t*v = %s_%s\n", rootIdx, goName, ToGoIdent(it.Name))
		}
		g.w("\t\tdefault:\n\t\t\treturn fmt.Errorf(\"unknown root enum index %%d for %s\", idx)\n\t\t}\n", goName)
		g.w("\t\treturn nil\n")
		g.w("\t}\n")

		g.w("\textIdx, err := r.ReadNormallySmallNonNegativeWholeNumber()\n\tif err != nil { return err }\n")
		g.w("\tswitch extIdx {\n")
		for extIdx, it := range typ.ExtensionItems {
			g.w("\tcase %d:\n\t\t*v = %s_%s\n", extIdx, goName, ToGoIdent(it.Name))
		}
		g.w("\tdefault:\n\t\t*v = %s(extIdx + 1000)\n", goName)
		g.w("\t}\n\treturn nil\n}\n\n")
	} else {
		g.w("\tidx, err := r.ReadConstrainedInt(0, %d)\n\tif err != nil { return err }\n", len(typ.Items)-1)
		g.w("\tswitch idx {\n")
		for rootIdx, it := range typ.Items {
			g.w("\tcase %d:\n\t\t*v = %s_%s\n", rootIdx, goName, ToGoIdent(it.Name))
		}
		g.w("\tdefault:\n\t\treturn fmt.Errorf(\"unknown enum index %%d for %s\", idx)\n\t}\n", goName)
		g.w("\treturn nil\n}\n\n")
	}
}

func (g *Generator) emitChoiceType(goName string, typ *ast.ChoiceType) {
	choiceEnum := goName + "Choice"
	g.w("// %s represents ASN.1 CHOICE selector tag\n", choiceEnum)
	g.w("type %s int\n\n", choiceEnum)
	g.w("const (\n")
	g.w("\t%s_None %s = 0\n", choiceEnum, choiceEnum)

	allAlts := append([]*ast.Alternative{}, typ.Alternatives...)
	allAlts = append(allAlts, typ.ExtensionAlternatives...)

	for i, alt := range allAlts {
		g.w("\t%s_%s %s = %d\n", choiceEnum, ToGoIdent(alt.Name), choiceEnum, i+1)
	}
	g.w(")\n\n")

	// Struct definition
	g.w("// %s represents ASN.1 CHOICE\n", goName)
	g.w("type %s struct {\n", goName)
	g.w("\tChoice %s\n", choiceEnum)
	for _, alt := range allAlts {
		altTypeStr := g.goTypeStr(alt.Type)
		g.w("\t%s *%s\n", ToGoIdent(alt.Name), altTypeStr)
	}
	g.w("}\n\n")

	// EncodeUPER
	g.w("func (v *%s) EncodeUPER(w *uper.BitWriter) error {\n", goName)
	g.w("\tswitch v.Choice {\n")
	for rootIdx, alt := range typ.Alternatives {
		altIdent := ToGoIdent(alt.Name)
		g.w("\tcase %s_%s:\n", choiceEnum, altIdent)
		if typ.Extensible {
			g.w("\t\tw.WriteBit(false)\n")
		}
		g.w("\t\tif err := w.WriteConstrainedInt(%d, 0, %d); err != nil { return err }\n", rootIdx, len(typ.Alternatives)-1)
		g.w("\t\tif v.%s == nil { return fmt.Errorf(\"choice alternative %s is nil\") }\n", altIdent, altIdent)
		g.emitValueEncode("(*v."+altIdent+")", alt.Type, "\t\t")
		g.w("\t\treturn nil\n")
	}

	for extIdx, alt := range typ.ExtensionAlternatives {
		altIdent := ToGoIdent(alt.Name)
		g.w("\tcase %s_%s:\n", choiceEnum, altIdent)
		g.w("\t\tw.WriteBit(true)\n")
		g.w("\t\tif err := w.WriteNormallySmallNonNegativeWholeNumber(%d); err != nil { return err }\n", extIdx)
		g.w("\t\tif v.%s == nil { return fmt.Errorf(\"extension choice alternative %s is nil\") }\n", altIdent, altIdent)
		g.w("\t\tsubW := uper.NewBitWriter()\n")
		g.emitValueEncodeWithWriter("(*v."+altIdent+")", alt.Type, "subW", "\t\t")
		g.w("\t\treturn w.WriteOpenType(subW.Bytes())\n")
	}

	g.w("\tdefault:\n\t\treturn fmt.Errorf(\"no choice alternative selected for %s\")\n\t}\n}\n\n", goName)

	// DecodeUPER
	g.w("func (v *%s) DecodeUPER(r *uper.BitReader) error {\n", goName)
	if typ.Extensible {
		g.w("\tisExt, err := r.ReadBit()\n\tif err != nil { return err }\n")
		g.w("\tif !isExt {\n")
		g.w("\t\tidx, err := r.ReadConstrainedInt(0, %d)\n\t\tif err != nil { return err }\n", len(typ.Alternatives)-1)
		g.w("\t\tswitch idx {\n")
		for rootIdx, alt := range typ.Alternatives {
			altIdent := ToGoIdent(alt.Name)
			altTypeStr := g.goTypeStr(alt.Type)
			g.w("\t\tcase %d:\n", rootIdx)
			g.w("\t\t\tv.Choice = %s_%s\n", choiceEnum, altIdent)
			g.w("\t\t\tvar val %s\n", altTypeStr)
			g.emitValueDecode("val", alt.Type, "\t\t\t")
			g.w("\t\t\tv.%s = &val\n", altIdent)
		}
		g.w("\t\tdefault:\n\t\t\treturn fmt.Errorf(\"unknown choice root index %%d for %s\", idx)\n\t\t}\n", goName)
		g.w("\t\treturn nil\n\t}\n")

		// Extension decode
		g.w("\textIdx, err := r.ReadNormallySmallNonNegativeWholeNumber()\n\tif err != nil { return err }\n")
		g.w("\topenBytes, err := r.ReadOpenType()\n\tif err != nil { return err }\n")
		g.w("\tsubR := uper.NewBitReader(openBytes)\n")
		g.w("\t_ = subR\n")
		g.w("\tswitch extIdx {\n")
		for extIdx, alt := range typ.ExtensionAlternatives {
			altIdent := ToGoIdent(alt.Name)
			altTypeStr := g.goTypeStr(alt.Type)
			g.w("\tcase %d:\n", extIdx)
			g.w("\t\tv.Choice = %s_%s\n", choiceEnum, altIdent)
			g.w("\t\tvar val %s\n", altTypeStr)
			g.emitValueDecodeWithReader("val", alt.Type, "subR", "\t\t")
			g.w("\t\tv.%s = &val\n", altIdent)
		}
		g.w("\tdefault:\n\t\t// Ignore unsupported future extension choice\n\t}\n\treturn nil\n}\n\n")
	} else {
		g.w("\tidx, err := r.ReadConstrainedInt(0, %d)\n\tif err != nil { return err }\n", len(typ.Alternatives)-1)
		g.w("\tswitch idx {\n")
		for rootIdx, alt := range typ.Alternatives {
			altIdent := ToGoIdent(alt.Name)
			altTypeStr := g.goTypeStr(alt.Type)
			g.w("\tcase %d:\n", rootIdx)
			g.w("\t\tv.Choice = %s_%s\n", choiceEnum, altIdent)
			g.w("\t\tvar val %s\n", altTypeStr)
			g.emitValueDecode("val", alt.Type, "\t\t")
			g.w("\t\tv.%s = &val\n", altIdent)
		}
		g.w("\tdefault:\n\t\treturn fmt.Errorf(\"unknown choice index %%d for %s\", idx)\n\t}\n\treturn nil\n}\n\n", goName)
	}
}

func (g *Generator) emitSequenceType(goName string, typ *ast.SequenceType) {
	g.w("// %s represents ASN.1 SEQUENCE\n", goName)
	g.w("type %s struct {\n", goName)

	for _, f := range typ.Fields {
		typeStr := g.goTypeStr(f.Type)
		if f.Optional {
			typeStr = "*" + typeStr
		}
		g.w("\t%s %s\n", ToGoIdent(f.Name), typeStr)
	}

	for _, f := range typ.ExtensionFields {
		typeStr := "*" + g.goTypeStr(f.Type)
		g.w("\t%s %s\n", ToGoIdent(f.Name), typeStr)
	}
	g.w("}\n\n")

	// EncodeUPER
	g.w("func (v *%s) EncodeUPER(w *uper.BitWriter) error {\n", goName)

	// Extensibility flag
	if typ.Extensible {
		if len(typ.ExtensionFields) > 0 {
			var extConds []string
			for _, f := range typ.ExtensionFields {
				extConds = append(extConds, fmt.Sprintf("v.%s != nil", ToGoIdent(f.Name)))
			}
			g.w("\thasExt := %s\n", strings.Join(extConds, " || "))
			g.w("\tw.WriteBit(hasExt)\n")
		} else {
			g.w("\tw.WriteBit(false)\n")
		}
	}

	// Preamble for root optional fields
	for _, f := range typ.Fields {
		if f.Optional {
			g.w("\tw.WriteBit(v.%s != nil)\n", ToGoIdent(f.Name))
		}
	}

	// Root fields encoding
	for _, f := range typ.Fields {
		fIdent := ToGoIdent(f.Name)
		if f.Optional {
			g.w("\tif v.%s != nil {\n", fIdent)
			g.emitValueEncode("(*v."+fIdent+")", f.Type, "\t\t")
			g.w("\t}\n")
		} else {
			g.emitValueEncode("v."+fIdent, f.Type, "\t")
		}
	}

	// Extension fields encoding
	if typ.Extensible && len(typ.ExtensionFields) > 0 {
		g.w("\tif hasExt {\n")
		g.w("\t\t// Determine highest present extension addition\n")
		g.w("\t\tnumAdditions := 0\n")
		for i, f := range typ.ExtensionFields {
			g.w("\t\tif v.%s != nil { numAdditions = %d }\n", ToGoIdent(f.Name), i+1)
		}
		g.w("\t\tif numAdditions > 0 {\n")
		g.w("\t\t\tif err := w.WriteNormallySmallNonNegativeWholeNumber(uint64(numAdditions - 1)); err != nil { return err }\n")
		for i, f := range typ.ExtensionFields {
			g.w("\t\t\tif %d < numAdditions {\n", i)
			g.w("\t\t\t\tw.WriteBit(v.%s != nil)\n", ToGoIdent(f.Name))
			g.w("\t\t\t}\n")
		}
		for i, f := range typ.ExtensionFields {
			fIdent := ToGoIdent(f.Name)
			g.w("\t\t\tif %d < numAdditions && v.%s != nil {\n", i, fIdent)
			g.w("\t\t\t\tsubW := uper.NewBitWriter()\n")
			g.emitValueEncodeWithWriter("(*v."+fIdent+")", f.Type, "subW", "\t\t\t\t")
			g.w("\t\t\t\tif err := w.WriteOpenType(subW.Bytes()); err != nil { return err }\n")
			g.w("\t\t\t}\n")
		}
		g.w("\t\t}\n")
		g.w("\t}\n")
	}

	g.w("\treturn nil\n}\n\n")

	// DecodeUPER
	g.w("func (v *%s) DecodeUPER(r *uper.BitReader) error {\n", goName)
	if typ.Extensible {
		g.w("\thasExt, err := r.ReadBit()\n\tif err != nil { return err }\n")
		if len(typ.ExtensionFields) == 0 {
			g.w("\tif hasExt {\n")
			g.w("\t\tkMinus1, err := r.ReadNormallySmallNonNegativeWholeNumber()\n\t\tif err != nil { return err }\n")
			g.w("\t\tfor i := 0; i < int(kMinus1)+1; i++ {\n")
			g.w("\t\t\tbit, err := r.ReadBit()\n\t\t\tif err != nil { return err }\n")
			g.w("\t\t\tif bit {\n")
			g.w("\t\t\t\tif _, err := r.ReadOpenType(); err != nil { return err }\n")
			g.w("\t\t\t}\n")
			g.w("\t\t}\n")
			g.w("\t}\n")
		}
	}

	// Preamble for root optional fields
	for _, f := range typ.Fields {
		if f.Optional {
			fIdent := ToGoIdent(f.Name)
			g.w("\tpresent_%s, err := r.ReadBit()\n\tif err != nil { return err }\n", fIdent)
		}
	}

	// Root fields decoding
	for _, f := range typ.Fields {
		fIdent := ToGoIdent(f.Name)
		typeStr := g.goTypeStr(f.Type)
		if f.Optional {
			g.w("\tif present_%s {\n", fIdent)
			g.w("\t\tvar val %s\n", typeStr)
			g.emitValueDecode("val", f.Type, "\t\t")
			g.w("\t\tv.%s = &val\n", fIdent)
			g.w("\t}\n")
		} else {
			g.emitValueDecode("v."+fIdent, f.Type, "\t")
		}
	}

	// Extension fields decoding
	if typ.Extensible && len(typ.ExtensionFields) > 0 {
		g.w("\tif hasExt {\n")
		g.w("\t\tkMinus1, err := r.ReadNormallySmallNonNegativeWholeNumber()\n\t\tif err != nil { return err }\n")
		g.w("\t\tnumExt := int(kMinus1) + 1\n")
		g.w("\t\textPresence := make([]bool, numExt)\n")
		g.w("\t\tfor i := 0; i < numExt; i++ {\n")
		g.w("\t\t\tbit, err := r.ReadBit()\n\t\t\tif err != nil { return err }\n\t\t\textPresence[i] = bit\n\t\t}\n")
		g.w("\t\tfor i := 0; i < numExt; i++ {\n")
		g.w("\t\t\tif extPresence[i] {\n")
		g.w("\t\t\t\topenBytes, err := r.ReadOpenType()\n\t\t\t\tif err != nil { return err }\n")
		g.w("\t\t\t\tsubR := uper.NewBitReader(openBytes)\n")
		g.w("\t\t\t\t_ = subR\n")
		g.w("\t\t\t\tswitch i {\n")
		for i, f := range typ.ExtensionFields {
			fIdent := ToGoIdent(f.Name)
			typeStr := g.goTypeStr(f.Type)
			g.w("\t\t\t\tcase %d:\n", i)
			g.w("\t\t\t\t\tvar val %s\n", typeStr)
			g.emitValueDecodeWithReader("val", f.Type, "subR", "\t\t\t\t\t")
			g.w("\t\t\t\t\tv.%s = &val\n", fIdent)
		}
		g.w("\t\t\t\tdefault:\n\t\t\t\t\t// Ignore unknown future extension addition\n\t\t\t\t}\n")
		g.w("\t\t\t}\n")
		g.w("\t\t}\n")
		g.w("\t}\n")
	}

	g.w("\treturn nil\n}\n\n")
}

func (g *Generator) emitValueEncode(valName string, t ast.Type, indent string) {
	g.emitValueEncodeWithWriter(valName, t, "w", indent)
}

func (g *Generator) emitValueEncodeWithWriter(valName string, t ast.Type, writerName string, indent string) {
	switch typ := t.(type) {
	case *ast.IntegerType:
		if typ.IsConstrained {
			g.w("%sif err := %s.WriteConstrainedInt(int64(%s), %d, %d); err != nil { return err }\n", indent, writerName, valName, typ.MinVal, typ.MaxVal)
		} else {
			g.w("%sif err := %s.WriteSemiConstrainedInt(int64(%s), 0); err != nil { return err }\n", indent, writerName, valName)
		}
	case *ast.BooleanType:
		g.w("%s%s.WriteBit(bool(%s))\n", indent, writerName, valName)
	case *ast.BitStringType:
		minSize := typ.MinSize
		maxSize := typ.MaxSize
		if !typ.HasSize {
			minSize = 0
			maxSize = 65535
		}
		g.w("%sif err := %s.WriteBitString(uper.BitString(%s), %d, %d); err != nil { return err }\n", indent, writerName, valName, minSize, maxSize)
	case *ast.OctetStringType:
		minSize := typ.MinSize
		maxSize := typ.MaxSize
		if !typ.HasSize {
			minSize = 0
			maxSize = 65535
		}
		g.w("%sif err := %s.WriteOctetString([]byte(%s), %d, %d); err != nil { return err }\n", indent, writerName, valName, minSize, maxSize)
	case *ast.CharacterStringType:
		minSize := typ.MinSize
		maxSize := typ.MaxSize
		if !typ.HasSize {
			minSize = 1
			maxSize = 255
		}
		if typ.Kind == "IA5String" {
			g.w("%sif err := %s.WriteIA5String(string(%s), %d, %d); err != nil { return err }\n", indent, writerName, valName, minSize, maxSize)
		} else {
			alphaRef := "nil"
			g.w("%sif err := %s.WriteVisibleString(string(%s), %s, %d, %d); err != nil { return err }\n", indent, writerName, valName, alphaRef, minSize, maxSize)
		}
	case *ast.UTCTimeType:
		g.w("%sif err := %s.WriteUTCTime(string(%s)); err != nil { return err }\n", indent, writerName, valName)
	case *ast.NullType:
		// NULL writes 0 bits
	case *ast.ReferenceType:
		g.w("%sif err := %s.EncodeUPER(%s); err != nil { return err }\n", indent, valName, writerName)
	case *ast.SequenceOfType:
		g.w("%sif err := %s.EncodeUPER(%s); err != nil { return err }\n", indent, valName, writerName)
	default:
		g.w("%sif err := %s.EncodeUPER(%s); err != nil { return err }\n", indent, valName, writerName)
	}
}

func (g *Generator) emitValueDecode(valName string, t ast.Type, indent string) {
	g.emitValueDecodeWithReader(valName, t, "r", indent)
}

func (g *Generator) emitValueDecodeWithReader(valName string, t ast.Type, readerName string, indent string) {
	switch typ := t.(type) {
	case *ast.IntegerType:
		if typ.IsConstrained {
			g.w("%s{\n", indent)
			g.w("%s\tdecodedVal, err := %s.ReadConstrainedInt(%d, %d)\n", indent, readerName, typ.MinVal, typ.MaxVal)
			g.w("%s\tif err != nil { return err }\n", indent)
			g.w("%s\t%s = decodedVal\n", indent, valName)
			g.w("%s}\n", indent)
		} else {
			g.w("%s{\n", indent)
			g.w("%s\tdecodedVal, err := %s.ReadSemiConstrainedInt(0)\n", indent, readerName)
			g.w("%s\tif err != nil { return err }\n", indent)
			g.w("%s\t%s = decodedVal\n", indent, valName)
			g.w("%s}\n", indent)
		}
	case *ast.BooleanType:
		g.w("%s{\n", indent)
		g.w("%s\tdecodedVal, err := %s.ReadBit()\n", indent, readerName)
		g.w("%s\tif err != nil { return err }\n", indent)
		g.w("%s\t%s = decodedVal\n", indent, valName)
		g.w("%s}\n", indent)
	case *ast.BitStringType:
		minSize := typ.MinSize
		maxSize := typ.MaxSize
		if !typ.HasSize {
			minSize = 0
			maxSize = 65535
		}
		g.w("%s{\n", indent)
		g.w("%s\tdecodedBs, err := %s.ReadBitString(%d, %d)\n", indent, readerName, minSize, maxSize)
		g.w("%s\tif err != nil { return err }\n", indent)
		g.w("%s\t%s = decodedBs\n", indent, valName)
		g.w("%s}\n", indent)
	case *ast.OctetStringType:
		minSize := typ.MinSize
		maxSize := typ.MaxSize
		if !typ.HasSize {
			minSize = 0
			maxSize = 65535
		}
		g.w("%s{\n", indent)
		g.w("%s\tdecodedBytes, err := %s.ReadOctetString(%d, %d)\n", indent, readerName, minSize, maxSize)
		g.w("%s\tif err != nil { return err }\n", indent)
		g.w("%s\t%s = decodedBytes\n", indent, valName)
		g.w("%s}\n", indent)
	case *ast.CharacterStringType:
		minSize := typ.MinSize
		maxSize := typ.MaxSize
		if !typ.HasSize {
			minSize = 1
			maxSize = 255
		}
		if typ.Kind == "IA5String" {
			g.w("%s{\n", indent)
			g.w("%s\tdecodedStr, err := %s.ReadIA5String(%d, %d)\n", indent, readerName, minSize, maxSize)
			g.w("%s\tif err != nil { return err }\n", indent)
			g.w("%s\t%s = decodedStr\n", indent, valName)
			g.w("%s}\n", indent)
		} else {
			alphaRef := "nil"
			g.w("%s{\n", indent)
			g.w("%s\tdecodedStr, err := %s.ReadVisibleString(%s, %d, %d)\n", indent, readerName, alphaRef, minSize, maxSize)
			g.w("%s\tif err != nil { return err }\n", indent)
			g.w("%s\t%s = decodedStr\n", indent, valName)
			g.w("%s}\n", indent)
		}
	case *ast.UTCTimeType:
		g.w("%s{\n", indent)
		g.w("%s\tdecodedStr, err := %s.ReadUTCTime()\n", indent, readerName)
		g.w("%s\tif err != nil { return err }\n", indent)
		g.w("%s\t%s = decodedStr\n", indent, valName)
		g.w("%s}\n", indent)
	case *ast.NullType:
		g.w("%s%s = uper.Null{}\n", indent, valName)
	case *ast.ReferenceType:
		g.w("%sif err := %s.DecodeUPER(%s); err != nil { return err }\n", indent, valName, readerName)
	case *ast.SequenceOfType:
		g.w("%sif err := %s.DecodeUPER(%s); err != nil { return err }\n", indent, valName, readerName)
	default:
		g.w("%sif err := %s.DecodeUPER(%s); err != nil { return err }\n", indent, valName, readerName)
	}
}
